apiVersion: v1
kind: Service
metadata:
  name: pagamento-api-mongo-service-temp
spec:
  type: NodePort
  selector:
    app: mongo-db
  ports:
    - port: 80
      targetPort: 27017
      nodePort: 30001
