apiVersion: v1
kind: Pod
metadata:
  name: pagamento-api-mongo
  labels:
    app: pagamento-api-mongo
spec:
  containers:
    - name: pagamento-api-mongo
      image: mongo
      ports:
        - containerPort: 27017
      env:
        - name: MONGO_DB_PORT
          value: "27017"
        - name: MONGO_DB_NAME
          value: "pagamento_db"