apiVersion: v1
kind: Service
metadata:
  name: pagamento-api-lb
  labels:
    app: pagamento-api-lb
spec:
  type: LoadBalancer
  selector:
    app: pagamento-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080